import {
  getAllPosts,
  getUserAllPosts,
  getUserPublishedPosts,
  getPostBySlug,
  getPostsByTagId,
  getAdminPostById,
  publishPost,
  deletePost,
  getPostReactions,
  handleImageUpload,
} from "./postAPI";
import {
  loginWithGoogle,
  loginWithUsername,
  preRegisterWithEmail,
  registerWithEmail,
  verifyToken,
} from "./authAPI";
import {
  reactOnPost,
  reactOnComment,
  getUserByUsername,
  followUser,
  checkUsername,
  updateUser,
  verifyEmail,
  getBookmarks,
  adminUpdateUser,
  deleteUser,
} from "./userAPI";
import { getAllAdminTags, searchTags, getAllTags } from "./tagAPI";
import { getCommentsWithContentId, addComment } from "./commentAPI";
module.exports = {
  getAllPosts,
  getUserAllPosts,
  getUserPublishedPosts,
  getPostBySlug,
  getPostsByTagId,
  getAdminPostById,
  publishPost,
  deletePost,
  getPostReactions,
  handleImageUpload,
  loginWithGoogle,
  loginWithUsername,
  preRegisterWithEmail,
  registerWithEmail,
  checkUsername,
  verifyToken,
  reactOnPost,
  reactOnComment,
  getUserByUsername,
  followUser,
  updateUser,
  verifyEmail,
  getBookmarks,
  adminUpdateUser,
  deleteUser,
  getAllAdminTags,
  searchTags,
  getAllTags,
  getCommentsWithContentId,
  addComment,
};
